### ISSUE TITLE
Inline buttons for links

### ISSUE THREAD

**Issue by pakshuang** [pakshuang/CS1010S-reminder-bot#1]
Instead of having the link to Coursemology as a hyperlink (see below), what if the link was in an inline button? There could also be a button to prompt users on the discussion group to subscribe to the channel itself. I was inspired by another channel (see below).

![image](https://user-images.githubusercontent.com/81917538/137141928-c14cc7a0-ecdf-48e8-9ef2-31b5a262d72f.png)
![image](https://user-images.githubusercontent.com/81917538/137142308-9f8429cc-1c24-4d09-ae7e-ce549646e6c7.png)

**Comment by RussellDash332** [comment]
One way to do this is using Telegram's InlineKeyboardMarkup. Good luck! 👍🏻
